[start]
command:/usr/local/etc/rc.d/mdns_bridge start
parameters:
type:script
description:Start mdns_bridge
message:starting mdns_bridge

[stop]
command:/usr/local/etc/rc.d/mdns_bridge stop
parameters:
type:script
description:Stop mdns_bridge
message:stopping mdns_bridge

[restart]
command:/usr/local/etc/rc.d/mdns_bridge restart
parameters:
type:script
description:Restart mdns_bridge
message:restarting mdns_bridge

[status]
command:/usr/local/etc/rc.d/mdns_bridge status; exit 0
parameters:
type:script_output
message:requesting mdns_bridge status
