# DO NOT EDIT THIS FILE -- OPNsense auto-generated file
{% if helpers.exists('OPNsense.mdnsbrdge.general.enabled') and OPNsense.mdnsbrdge.general.enabled|default("0") == "1" %}
mdns_bridge_enable="YES"
{% else %}
mdns_bridge_enable="NO"
{% endif %}
